import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['DM Sans', ...defaultTheme.fontFamily.sans],
                headline: ['DM Sans', 'sans-serif'],
                display: ['DM Sans', 'sans-serif'],
                body: ['DM Sans', 'sans-serif'],
                label: ['DM Sans', 'sans-serif'],
            },
            colors: {
                "background": "#fef7ff",
                "on-tertiary-fixed-variant": "#005580",
                "inverse-surface": "#2e1a28",
                "outline": "#907898",
                "surface-tint": "#e040a0",
                "on-tertiary-container": "#00334d",
                "on-tertiary-fixed": "#001a33",
                "tertiary-fixed": "#c8eaff",
                "surface-container": "#f8eef8",
                "surface-dim": "#e0d6e0",
                "primary-fixed": "#ffd6ee",
                "inverse-primary": "#f0a0cc",
                "tertiary-container": "#40c0ee",
                "tertiary": "#0096cc",
                "error-container": "#ffe8e8",
                "tertiary-fixed-dim": "#80d0f0",
                "on-secondary": "#ffffff",
                "surface-container-high": "#f2e8f2",
                "on-error-container": "#9b1c1c",
                "on-surface": "#2e1a28",
                "on-secondary-fixed-variant": "#4a3068",
                "on-secondary-container": "#2e2040",
                "surface-variant": "#f2e8f2",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#ece2ec",
                "primary-fixed-dim": "#f0a0cc",
                "surface-container-low": "#fbf2fb",
                "primary": "#e040a0",
                "outline-variant": "#dcc8e0",
                "on-primary-fixed": "#3d0028",
                "surface": "#fef7ff",
                "secondary-fixed": "#eedcff",
                "primary-container": "#f080c0",
                "on-tertiary": "#ffffff",
                "inverse-on-surface": "#fef7ff",
                "secondary-container": "#eedcff",
                "surface-bright": "#fef7ff",
                "on-surface-variant": "#604868",
                "on-primary-fixed-variant": "#a02070",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#c8a8e8",
                "on-background": "#2e1a28",
                "on-primary-container": "#2e1a28",
                "on-primary": "#ffffff",
                "error": "#e53e3e",
                "on-secondary-fixed": "#1a1030",
                "secondary": "#7c52aa",
                "success": "#22c55e"
            },
            borderRadius: {
                "DEFAULT": "0.375rem",
                "sm": "0.25rem",
                "md": "0.375rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                "full": "9999px"
            },
        },
    },

    plugins: [forms],
};
